---
# main playbook file for register_LDAP

- name: Register user in the LDAP server
  hosts: all
  become: false
  pre_tasks:
    - name: Get highest uid
      shell: "set -o pipefail && {{ get_highest_uid_command }}"
      args:
        executable: /bin/bash
      register: uid_result
      changed_when: false
      when: uid is not defined
      tags: get_uid

    - name: Set uid
      set_fact:
        uid: "{{ uid_result.stdout | int + 1 }}"
      when: uid is not defined
      tags: get_uid

    - name: Show uid
      debug:
        var: uid
      tags: get_uid
  tasks:
    - name: Register user in the LDAP server
      ldap_entry:
        dn: "cn={{ full_name }},{{ users_base_DN }}"
        objectClass:
          - inetOrgPerson
          - posixAccount
          - top
        server_uri: "{{ server_uri }}"
        start_tls: false
        validate_certs: "{{ testing is undefined and validate_certs }}"
        bind_dn: "{{ bind_DN }}"
        bind_pw: "{{ bind_credentials }}"
        attributes:
          userPassword: "{{ password }}"
          mail: "{{ email }}"
          gidNumber: "{{ gid }}"
          givenName: "{{ user_name }}"
          sn: "{{ surname }}"
          homeDirectory: "{{ home_directory }}"
          uidNumber: "{{ uid }}"
          uid: "{{ nick }}"
